---
- name: Install Arduino dependencies
  ansible.builtin.package:
    name: "{{ arduino_packages }}"
    state: present

- name: Install Arduino IDE
  ansible.builtin.include_tasks:
    file: ide.yml
  when:
    - arduino_ide_version | length > 0
    - arduino_ide_download_url | length > 0

- name: Configure Arduino CLI
  ansible.builtin.include_tasks:
    file: config.yml
  when: arduino_board_manager_urls | length > 0

