- name: Setup
  hosts: localhost
  vars:
    setup_username: lawrence

    dnf_cli_packages:
      - neovim
      - fish
      - tmux
      - uv
      - htop
      - fd-find

    dnf_virtualization_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - qemu
      - "@virtualization"
      - libvirt
      - nvidia-container-toolkit
      - nvidia-container-toolkit-selinux

    dnf_gui_packages:
      - alacritty
      - fedora-workstation-repositories
      - google-chrome-stable
      - steam

    dnf_nvidia_driver_packages:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda

    flatpak_gui_packages:
      - org.telegram.desktop
      - md.obsidian.Obsidian
      - com.mikrotik.WinBox
      - com.usebottles.bottles
      - com.belmoussaoui.Authenticator
      - com.discordapp.Discord

  tasks:
    - name: Add DNF repos
      ansible.builtin.yum_repository:
        name: Docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
        gpgcheck: false
        enabled: true
      become: true

    - name: Enable Fedora COPR repository
      community.general.copr:
        state: enabled
        name: "@ai-ml/nvidia-container-toolkit"
      become: yes

    - name: Install DNF packages
      ansible.builtin.dnf5:
        name: >-
          {{
            dnf_cli_packages
            + dnf_virtualization_packages
            + dnf_gui_packages
            + dnf_nvidia_driver_packages
          }}
        state: present
      become: true

    - name: Generate CDI Configuration
      ansible.builtin.shell: "nvidia-ctk cdi generate -output /etc/cdi/nvidia.yaml"
      args:
        creates: "/etc/cdi/nvidia.yaml"
      become: yes

    - name: Add Flathub remote repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Flatpak GUI Software
      community.general.flatpak:
        name: "{{ flatpak_gui_packages }}"          
        state: present
        remote: flathub
        method: system
      become: yes

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
      become: true

    - name: Setup fish for user
      block:
        - name: Find the absolute path of fish
          ansible.builtin.command: which fish
          register: fish_path
          changed_when: false
          failed_when: fish_path.rc != 0

        - name: Ensure fish is registered in /etc/shells
          ansible.builtin.lineinfile:
            path: /etc/shells
            line: "{{ fish_path.stdout.strip() }}"
            create: true
            mode: "0644"
          become: yes

        - name: Set fish as the default login shell for the user
          ansible.builtin.user:
            name: "{{ setup_username }}"
            shell: "{{ fish_path.stdout.strip() }}"
          become: yes

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ setup_username }}"
        groups:
          - docker
        append: true
      become: true

    - name: Install Lazyvim
      ansible.builtin.git:
        repo: "git@github.com:prostoLavr/lazy.git"
        dest: "/home/{{ setup_username }}/.config/nvim"
        clone: yes
        update: no

    - name: Inttall Terraform
      ansible.builtin.unarchive:
        src: "https://mirror.yandex.ru/mirrors/releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip"
        dest: "/usr/local/bin/"
        remote_src: yes
        include:
          - "terraform"
        creates: "/usr/loca/bin/terraform"
        mode: "755"
      become: yes

    - name: Install Minikube
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'
        owner: root
        group: root
