- name: Setup
  hosts: localhost
  vars:
    setup_username: lawrence
    arduino_ide_version: "2.3.2"
    terraform_version: "1.9.8"
    install_dir: /opt/arduino-ide
    minikube_version: "1.38.1"

    terraform_download_url: "https://mirror.yandex.ru/mirrors/releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    minikube_download_url: "https://storage.googleapis.com/minikube/releases/v{{ minikube_version }}/minikube-linux-amd64"
    arduino_download_url: "https://downloads.arduino.cc/arduino-ide/arduino-ide_{{ arduino_ide_version }}_Linux_64bit.zip"

    dnf_cli_packages:
      - neovim
      - fish
      - tmux
      - uv
      - htop
      - fd-find
      - git
      - curl
      - wget
      - gcc
      - gcc-c++
      - make
      - cmake
      - pkg-config
      - python3-devel
      - kernel-devel
      - kernel-headers
      - openssl-devel
      - ripgrep
      - fzf
      - btop
      - zoxide

    dnf_virtualization_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - qemu
      - "@virtualization"
      - libvirt
      - nvidia-container-toolkit
      - nvidia-container-toolkit-selinux
      - conntrack
      - crictl
      - cri-tools
      - kubectl

    dnf_gui_packages:
      - alacritty
      - fedora-workstation-repositories
      - google-chrome-stable
      - steam

    dnf_nvidia_driver_packages:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda

    flatpak_gui_packages:
      - org.telegram.desktop
      - md.obsidian.Obsidian
      - com.mikrotik.WinBox
      - com.usebottles.bottles
      - com.belmoussaoui.Authenticator
      - com.discordapp.Discord

    dnf_asus_packages:
      - fwupd
      - asusctl
      - supergfxctl
      - power-profiles-daemon

  tasks:
    - name: Add DNF repos
      ansible.builtin.yum_repository:
        name: Docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
        gpgcheck: false
        enabled: true
      become: true

    - name: Enable Fedora COPR repository
      community.general.copr:
        state: enabled
        name: "@ai-ml/nvidia-container-toolkit"
      become: yes

    - name: Install DNF packages
      ansible.builtin.dnf5:
        name: >-
          {{
            dnf_cli_packages
            + dnf_virtualization_packages
            + dnf_gui_packages
            + dnf_nvidia_driver_packages
          }}
        state: present
      become: true

    - name: Generate Nvidia CDI configuration
      ansible.builtin.command:
        cmd: "nvidia-ctk cdi generate -output /etc/cdi/nvidia.yaml"
      creates: "/etc/cdi/nvidia.yaml"
      become: yes

    - name: Add Flathub remote repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: yes

    - name: Flatpak GUI Software
      community.general.flatpak:
        name: "{{ flatpak_gui_packages }}"          
        state: present
        remote: flathub
        method: system
      become: yes

    - name: Enable and started Docker service (no restart)
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
      become: true

    - name: Setup fish for user
      block:
        - name: Find the absolute path of fish
          ansible.builtin.command: command -v fish
          register: fish_path
          changed_when: false
          failed_when: fish_path.rc != 0

        - name: Ensure fish is registered in /etc/shells
          ansible.builtin.lineinfile:
            path: /etc/shells
            line: "{{ fish_path.stdout.strip() }}"
            create: true
            mode: "0644"
          become: yes

        - name: Set fish as the default login shell for the user
          ansible.builtin.user:
            name: "{{ setup_username }}"
            shell: "{{ fish_path.stdout.strip() }}"
          become: yes

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ setup_username }}"
        groups:
          - docker
        append: true
      become: true

    - name: Install Lazyvim
      ansible.builtin.git:
        repo: "git@github.com:prostoLavr/lazy.git"
        dest: "/home/{{ setup_username }}/.config/nvim"
        clone: yes
        update: no

    - name: Install Terraform
      community.general.unarchive:
        src: "{{ terraform_download_url }}"
        dest: "/usr/local/bin/"
        remote_src: yes
        include:
          - "terraform"
        creates: "/usr/local/bin/terraform"
        mode: "755"
      become: yes

    - name: Install Minikube
      ansible.builtin.get_url:
        url: "{{ minikube_download_url }}"
        dest: /usr/local/bin/minikube
        mode: '0755'
        owner: root
        group: root
    - name: Configure Arduino IDE and ESP32 Dev Environment on Fedora
      become: yes
      block: 
        - name: Install system dependencies 
          ansible.builtin.dnf5: 
            name: 
              - python3-pip
              - python3-pyserial
              - libnsl
              - unzip
            state: present

        - name: Create Arduino IDE installation directory
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            mode: '0755'

        - name: Download and extract Arduino IDE
          ansible.builtin.unarchive:
            src: "{{ arduino_download_url }}"
            dest: "{{ install_dir }}"
            remote_src: yes
            extra_opts: [--strip-components=1]
          creates: "{{ install_dir }}/arduino-ide"

        - name: Ensure correct ownership of installation directory
          ansible.builtin.file:
            path: "{{ install_dir }}"
            recurse: yes
            owner: root
            group: root

        - name: Create symlink in system PATH
          ansible.builtin.file:
            src: "{{ install_dir }}/arduino-ide"
            dest: "/usr/local/bin/arduino-ide"
            state: link

        - name: Add user to dialout group for CH340 serial access
          ansible.builtin.user:
            name: "{{ setup_username }}"
            groups: 
              - uucp
              - lock
            append: yes

        - name: Configure ESP32 Board Manager URL for Arduino IDE
          block:
            - name: Ensure Arduino configuration directory exists
              ansible.builtin.file:
                path: "{{ setup_username }}/.arduinoIDE"
                state: directory
                mode: '0755'
              become: yes
              become_user: "{{ setup_username }}"

        - name: Add ESP32 URL to arduino-cli.yaml
          ansible.builtin.copy:
            dest: "{{ ansible_env.HOME }}/.arduinoIDE/arduino-cli.yaml"
            content: |
              board_manager:
                additional_urls:
                - https://espressif.github.io/arduino-esp32/package_esp32_index.json
            mode: '0644'
          become: yes
          become_user: "{{ setup_username }}"

        - name: Create Desktop Entry for easy launching
          ansible.builtin.copy:
            dest: "/usr/share/applications/arduino-ide.desktop"
            content: |
              [Desktop Entry]
              Type=Application
              Name=Arduino IDE
              GenericName=Arduino IDE
              Comment=Open-source electronics prototyping platform
              Exec=/usr/local/bin/arduino-ide %F
              Icon={{ install_dir }}/resources/app/lib/backend/resources/arduino.png
              Terminal=false
              Categories=Development;Engineering;
              MimeType=text/x-arduino;
            mode: '0644'
