all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_pass: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        38623265323664396335656635663537353937313863356565316162393866663039653032353564
        6235383032326535353233646531353337303861343466640a313665636663363532666664636662
        66646632346332363537306230626139333636643764346538323133663233393564383064306566
        6331626537383865610a333464623334653864363930613333323638323532366134346239393939
        3863
  children:
    workstation:
      hosts:
        localhost:

      children:
        cli:
          hosts:
            localhost:

        dev:
          hosts:
            localhost:

        containers:
          hosts:
            localhost:

        kubernetes:
          hosts:
            localhost:

        virtualization:
          hosts:
            localhost:

        nvidia:
          hosts:
            localhost:

        desktop:
          hosts:
            localhost:

        gaming:
          hosts:
            localhost:

        audio:
          hosts:
            localhost:

        music:
          hosts:
            localhost:

        arduino:
          hosts:
            localhost:

        network:
          hosts:
            localhost:

        firmware:
          hosts:
            localhost:

        asus:
          hosts:
            localhost:

