---
arduino_packages:
  - python3-pyserial
  - libnsl

arduino_esp32_board_manager_url:
  "https://espressif.github.io/arduino-esp32/package_esp32_index.json"

arduino_download_url: >-
  https://downloads.arduino.cc/arduino-ide/
  arduino-ide_{{ arduino_ide_version }}_Linux_64bit.zip

