---
cli_packages:
  - neovim
  - fish
  - tmux
  - fzf
  - fd-find
  - ripgrep
  - zoxide
  - tree

cli_shell: /usr/bin/fish

nvim_configuration_repo: "https://github.com/prostoLavr/lazy.git"
nvim_configuration_path: "{{ ansible_facts['user_dir'] }}/.config/nvim"

