---
containers_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - podman
  - podman-compose

  - conntrack
  - cri-tools
  - crictl
  - socat
  - ebtables
  - iptables

containers_enable_docker: true

containers_docker_repository:
  url: "https://download.docker.com/linux/fedora/docker-ce.repo"
  dest: "/etc/yum.repos.d/docker-ce.repo"

