---
dev_packages:
  - gcc
  - gcc-c++
  - clang
  - llvm
  - lld
  - make
  - cmake
  - ninja-build
  - just
  - pkg-config
  - python3-devel
  - python3-pip
  - openssl-devel
  - uv
  - php-cli
  - php-zip
  - composer

terraform_version: "1.9.8"

terraform_download_url: >-
  https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip

terragrunt_version: "1.1.1"

terragrunt_download_url: >-
  https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64

