---
nvidia_packages:
  - akmod-nvidia
  - xorg-x11-drv-nvidia-cuda
  - nvidia-modprobe
  - kernel-devel
  - kernel-headers

nvidia_container_packages:
  - nvidia-container-toolkit

nvidia_repository_url: >-
  https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo

nvidia_cdi_output: /etc/cdi/nvidia.yaml

