---
nvidia_packages:
  - akmod-nvidia
  - xorg-x11-drv-nvidia-cuda
  - nvidia-modprobe
  - nvidia-container-toolkit
  - nvidia-container-toolkit-selinux
  - kernel-devel
  - kernel-headers

nvidia_copr_repositories:
  - "@ai-ml/nvidia-container-toolkit"

nvidia_cdi_config: "/etc/cdi/nvidia.yaml"

