---
- name: Refresh firmware metadata
  ansible.builtin.command:
    cmd: fwupdmgr refresh
  register: fwupdmgr_refresh
  changed_when: >-
    'Metadata is up to date' not in
    (fwupdmgr_refresh.stdout + fwupdmgr_refresh.stderr)

- name: Check available firmware updates
  ansible.builtin.command:
    cmd: fwupdmgr get-updates
  register: fwupdmgr_updates
  changed_when: false
  failed_when: false

- name: Show available firmware updates
  ansible.builtin.debug:
    var: fwupdmgr_updates.stdout_lines

