---
- name: Refresh firmware metadata
  ansible.builtin.command:
    argv:
      - fwupdmgr
      - refresh
  register: fwupdmgr_refresh
  changed_when: false
  become: true

- name: Check firmware updates
  ansible.builtin.command:
    argv:
      - fwupdmgr
      - get-updates
  register: fwupdmgr_updates
  changed_when: false
  failed_when: false
  become: true

- name: Show available firmware updates
  ansible.builtin.debug:
    msg: "{{ fwupdmgr_updates.stdout_lines }}"
  when: fwupdmgr_updates.stdout | length > 0

