---
- name: Check installed Minikube
  ansible.builtin.command:
    cmd: minikube version --output=json
  register: minikube_installed
  changed_when: false
  failed_when: false

- name: Install Minikube
  when: >
    minikube_installed.rc != 0 or
    ('v' ~ minikube_version) not in minikube_installed.stdout
  block:

    - name: Define Minikube URL
      ansible.builtin.set_fact:
        minikube_download_url: >-
          https://storage.googleapis.com/minikube/releases/
          v{{ minikube_version }}/minikube-linux-{{ binary_arch }}

    - name: Download Minikube
      ansible.builtin.get_url:
        url: "{{ minikube_download_url | replace('\n', '') | replace(' ', '') }}"
        dest: /usr/local/bin/minikube
        owner: root
        group: root
        mode: "0755"
      become: true

