---
- name: Get setup user information
  ansible.builtin.getent:
    database: passwd
    key: "{{ setup_username }}"

- name: Set setup user home
  ansible.builtin.set_fact:
    setup_user_home: "{{ getent_passwd[setup_username][4] }}"

- name: Ensure Neovim config directory exists
  ansible.builtin.file:
    path: "{{ setup_user_home }}/.config"
    state: directory
    owner: "{{ setup_username }}"
    group: "{{ setup_username }}"
    mode: "0755"
  become: true

- name: Install Neovim configuration
  ansible.builtin.git:
    repo: "{{ nvim_configuration_repo }}"
    dest: "{{ setup_user_home }}/.config/nvim"
    clone: true
    update: true
    accept_hostkey: true
  become: true
  become_user: "{{ setup_username }}"

