---
- name: Build user groups
  ansible.builtin.set_fact:
    workstation_user_groups: >-
      {{
        []
        + (['docker'] if 'containers' in group_names else [])
        + (['libvirt'] if 'virtualization' in group_names else [])
        + (['lock', 'dialout'] if 'arduino' in group_names else [])
      }}

- name: Find fish
  ansible.builtin.command:
    cmd: command -v fish
  register: fish_path
  changed_when: false

- name: Register fish in /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout | trim }}"
    create: true
    mode: "0644"
  become: true

- name: Configure setup user
  ansible.builtin.user:
    name: "{{ setup_username }}"
    shell: "{{ fish_path.stdout | trim }}"
    groups: "{{ workstation_user_groups }}"
    append: true
  become: true

