---
- name: Check installed Terragrunt
  ansible.builtin.command:
    cmd: terragrunt --version
  register: terragrunt_installed
  changed_when: false
  failed_when: false

- name: Install Terragrunt
  when: >
    terragrunt_installed.rc != 0 or
    terragrunt_version not in terragrunt_installed.stdout
  block:

    - name: Define Terragrunt URL
      ansible.builtin.set_fact:
        terragrunt_download_url: >-
          https://github.com/gruntwork-io/terragrunt/releases/download/
          v{{ terragrunt_version }}/terragrunt_linux_{{ binary_arch }}

    - name: Download Terragrunt
      ansible.builtin.get_url:
        url: "{{ terragrunt_download_url | replace('\n', '') | replace(' ', '') }}"
        dest: /usr/local/bin/terragrunt
        owner: root
        group: root
        mode: "0755"
      become: true

