- name: Setup
  hosts: localhost
  vars:
    setup_username: lawrence
    arduino_ide_version: "2.3.2"
    terraform_version: "1.9.8"
    terragrunt_version: "1.1.1"
    install_dir: /opt/arduino-ide
    minikube_version: "1.38.1"
    # TODO: Calculate fedora version
    remi_repo_url: "https://rpms.remirepo.net/fedora/remi-release-44.rpm"

    terraform_download_url: "https://mirror.yandex.ru/mirrors/releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    arduino_download_url: "https://downloads.arduino.cc/arduino-ide/arduino-ide_{{ arduino_ide_version }}_Linux_64bit.zip"
    composer_installer_download_url: "https://getcomposer.org/installer"

    binary_downloads:
      - name: "minikube"
        url: "https://storage.googleapis.com/minikube/releases/v{{ minikube_version }}/minikube-linux-amd64"
      - name: "terragrunt"
        url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"

    dnf_cli_packages:
      - neovim
      - fish
      - tmux
      - git
      - curl
      - wget
      - htop
      - btop
      - tree
      - jq
      - fd-find
      - ripgrep
      - fzf
      - zoxide
      - lsof
      - strace
      - tcpdump
      - nmap
      - bind-utils
      - rsync
      - unzip
      - zip

    dnf_dev_packages:
      - gcc
      - gcc-c++
      - clang
      - llvm
      - lld
      - make
      - cmake
      - ninja-build
      - just
      - pkg-config
      - python3-devel
      - python3-pip
      - openssl-devel
      - uv
      - php-cli
      - php-zip
      - composer

    dnf_container_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - podman
      - podman-compose
      - qemu
      - libvirt
      - virt-manager
      - virt-install
      - bridge-utils
      - "@virtualization"
#       - kubectl
      - conntrack
      - cri-tools
      - crictl
      - socat
      - ebtables
      - iptables
      - qemu-kvm
      - libvirt-daemon-kvm
      - virt-install
      - cloud-init


    dnf_gui_packages:
      - alacritty
      - fedora-workstation-repositories
      - google-chrome-stable
      - steam

    dnf_nvidia_packages:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - nvidia-modprobe
      - nvidia-container-toolkit
      - nvidia-container-toolkit-selinux
      - kernel-devel
      - kernel-headers

    flatpak_gui_packages:
      - org.telegram.desktop
      - md.obsidian.Obsidian
      - com.mikrotik.WinBox
      - com.usebottles.bottles
      - com.belmoussaoui.Authenticator
      - com.discordapp.Discord

    dnf_asus_packages:
      - asusctl
      - supergfxctl
      - switcheroo-control
      - tuned
      - tuned-ppd
#       - power-profiles-daemon
      - fwupd
      - lm_sensors
      - powertop
      - nvtop
      - stress-ng
      - usbutils
      - pciutils
      - vulkan-tools
      - mesa-demos

    dnf_arduino_packages:
      - python3-pyserial
      - libnsl

    dnf_network_packages:
      - wireguard-tools
      - openvpn

    dnf_shell_packages:
      - bash-completion
      - fish

    dnf_rpm_fusion_repos:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version']  }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"

  tasks:
    
    - name: Enable DNF repositories
      ansible.builtin.dnf5:
        name: "{{ dnf_rpm_fusion_repos }}"
        state: present
        disable_gpg_check: true
      become: true

    - name: Enable Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'
      become: true

    - name: Install Fedora Workstation repositories
      ansible.builtin.dnf5:
        name: fedora-workstation-repositories
        state: present
      become: true

    - name: Enable Google Chrome repository
      ansible.builtin.command:
        argv:
          - dnf
          - config-manager
          - setopt
          - google-chrome.enabled=1
      changed_when: false
      become: true

    - name: Enable Fedora COPR repository
      community.general.copr:
        state: enabled
        name: "@ai-ml/nvidia-container-toolkit"
      become: yes

    - name: Add Remi repo
      ansible.builtin.dnf5:
        name: "{{ remi_repo_url }}"
        state: present
        disable_gpg_check: true
      become: true

    - name: Install DNF packages
      ansible.builtin.dnf5:
        update_cache: true
        name: >-
          {{
            dnf_cli_packages
            + dnf_dev_packages
            + dnf_container_packages
            + dnf_nvidia_packages
            + dnf_asus_packages
            + dnf_gui_packages
            + dnf_arduino_packages
            + dnf_network_packages
            + dnf_shell_packages
          }}
        state: present
      become: true

    - name: Generate Nvidia CDI configuration
      ansible.builtin.command:
        argv:
          - nvidia-ctk
          - cdi
          - generate
          - -output
          - /etc/cdi/nvidia.yaml
        creates: "/etc/cdi/nvidia.yaml"
      become: yes

    - name: Add Flathub remote repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: yes

    - name: Flatpak GUI Software
      community.general.flatpak:
        name: "{{ flatpak_gui_packages }}"          
        state: present
        remote: flathub
        method: system
      become: yes

    - name: Enable and started Docker service (no restart)
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
      become: true

    - name: Find the absolute path of fish
      ansible.builtin.command:
        cmd: "command -v fish"
      register: fish_path
      changed_when: false
      failed_when: fish_path.rc != 0

    - name: Ensure fish is registered in /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "{{ fish_path.stdout.strip() }}"
        create: true
        mode: "0644"
      become: yes

    - name: Setup user default shell and groups
      ansible.builtin.user:
        name: "{{ setup_username }}"
        shell: "{{ fish_path.stdout.strip() }}"
        groups:
          - docker
          - libvirt
          - lock
          - dialout
        append: true
      become: true

    - name: Install Lazyvim
      ansible.builtin.git:
        repo: "git@github.com:prostoLavr/lazy.git"
        dest: "/home/{{ setup_username }}/.config/nvim"
        clone: yes
        update: no
      become: true
      become_user: "{{ setup_username }}"

    - name: Install Terraform
      ansible.builtin.unarchive:
        src: "{{ terraform_download_url }}"
        dest: "/usr/local/bin/"
        remote_src: yes
        include:
          - "terraform"
        creates: "/usr/local/bin/terraform"
        mode: "755"
      become: yes
    
    - name: Install binaries
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "/usr/local/bin/{{ item.name }}"
        mode: '0755'
        owner: root
        group: root
      loop: "{{ binary_downloads }}"
      become: true

    - name: Configure Arduino IDE and ESP32 Dev Environment on Fedora
      become: yes
      when: false
      block: 
        - name: Create Arduino IDE installation directory
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            mode: '0755'

        - name: Download and extract Arduino IDE
          ansible.builtin.unarchive:
            src: "{{ arduino_download_url }}"
            dest: "{{ install_dir }}"
            remote_src: yes
            extra_opts: [--strip-components=1]
            creates: "{{ install_dir }}/arduino-ide"

        - name: Ensure correct ownership of installation directory
          ansible.builtin.file:
            path: "{{ install_dir }}"
            recurse: yes
            owner: root
            group: root

        - name: Create symlink in system PATH
          ansible.builtin.file:
            src: "{{ install_dir }}/arduino-ide"
            dest: "/usr/local/bin/arduino-ide"
            state: link

        - name: Configure ESP32 Board Manager URL for Arduino IDE
          block:
            - name: Ensure Arduino configuration directory exists
              ansible.builtin.file:
                path: "/home/{{ setup_username }}/.arduinoIDE"
                state: directory
                mode: '0755'
              become: yes
              become_user: "{{ setup_username }}"

        - name: Add ESP32 URL to arduino-cli.yaml
          ansible.builtin.copy:
            dest: "/home/{{ setup_username }}/.arduinoIDE/arduino-cli.yaml"
            content: |
              board_manager:
                additional_urls:
                - https://espressif.github.io/arduino-esp32/package_esp32_index.json
            mode: '0644'
          become: yes
          become_user: "{{ setup_username }}"

        - name: Create Desktop Entry for easy launching
          ansible.builtin.copy:
            dest: "/usr/share/applications/arduino-ide.desktop"
            content: |
              [Desktop Entry]
              Type=Application
              Name=Arduino IDE
              GenericName=Arduino IDE
              Comment=Open-source electronics prototyping platform
              Exec=/usr/local/bin/arduino-ide %F
              Icon={{ install_dir }}/resources/app/lib/backend/resources/arduino.png
              Terminal=false
              Categories=Development;Engineering;
              MimeType=text/x-arduino;
            mode: '0644'

    - name: Asus fwupdmgr (Step 1)
      ansible.builtin.command: 
        argv:
          - fwupdmgr
          - refresh
      become: yes
      register: fwupdmgr_refresh_result
      changed_when: "'Metadata is up to date' is not in fwupdmgr_refresh_result.stderr"
      failed_when: "'Metadata is up to date' is not in fwupdmgr_refresh_result.stderr and fwupdmgr_refresh_result.rc != 0"

    - name: Asus fwupdmgr (Step 2)
      ansible.builtin.command:
        argv:
          - fwupdmgr
          - get-updates
      become: yes
