---
- name: Configure workstation
  hosts: workstation
  become: true
  gather_facts: true

  roles:
    - role: common
      tags:
        - common
        - always

    - role: cli
      when: "'cli' in group_names"
      tags:
        - cli

    - role: dev
      when: "'dev' in group_names"
      tags:
        - dev

    - role: containers
      when: "'containers' in group_names"
      tags:
        - containers

    - role: kubernetes
      when: "'kubernetes' in group_names"
      tags:
        - kubernetes

    - role: virtualization
      when: "'virtualization' in group_names"
      tags:
        - virtualization

    - role: nvidia
      when: "'nvidia' in group_names"
      tags:
        - nvidia

    - role: amd
      when: "'amd' in group_names"
      tags:
        - amd

    - role: desktop
      when: "'desktop' in group_names"
      tags:
        - desktop

    - role: browser
      when: "'browser' in group_names"
      tags:
        - browser

    - role: flatpak
      when: "'flatpak' in group_names"
      tags:
        - flatpak

    - role: gaming
      when: "'gaming' in group_names"
      tags:
        - gaming

    - role: arduino
      when: "'arduino' in group_names"
      tags:
        - arduino

    - role: asus
      when: "'asus' in group_names"
      tags:
        - asus

    - role: media
      when: "'media' in group_names"
      tags:
        - media

    - role: music
      when: "'music' in group_names"
      tags:
        - music

    - role: music
      when: "'music' in group_names"
      tags:
        - music

    - role: music
      when: "'music' in group_names"
      tags:
        - music

