---
- name: Ensure CDI directory exists
  ansible.builtin.file:
    path: "{{ nvidia_cdi_output | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Generate NVIDIA CDI configuration
  ansible.builtin.command:
    cmd: >-
      nvidia-ctk cdi generate
      --output={{ nvidia_cdi_output }}
  register: nvidia_cdi
  changed_when: true
  failed_when: false

