---
- name: Install NVIDIA Container Toolkit
  ansible.builtin.package:
    name: "{{ nvidia_container_packages }}"
    state: present

- name: Configure NVIDIA Container Toolkit for Docker
  ansible.builtin.command:
    cmd: nvidia-ctk runtime configure --runtime=docker
  register: nvidia_docker_config
  changed_when: nvidia_docker_config.rc == 0
  when:
    - nvidia_configure_container_runtime
    - "'containers' in group_names"
  notify:
    - Restart Docker

